# core/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model # If projects are linked to users

# Assuming you have a BRD model in your 'brd' app
# from brd.models import Brd

User = get_user_model()

class Project(models.Model):
    """
    Represents a software project generated by the AI based on a BRD.
    """
    name = models.CharField(max_length=255, help_text="Name of the generated project")
    description = models.TextField(blank=True, null=True, help_text="Summary of the project generated by AI")
    
    # Link to the original BRD if you have a model for it in 'brd' app
    # brd = models.ForeignKey(Brd, on_delete=models.SET_NULL, null=True, blank=True,
    #                         help_text="The Business Requirement Document this project was generated from.")
    
    # Link to the user who initiated the generation
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='generated_projects',
                              help_text="The user who initiated this project generation.")

    # Status of the generation process
    STATUS_CHOICES = [
        ('PENDING', 'Pending Generation'),
        ('GENERATING', 'Generating'),
        ('COMPLETED', 'Completed'),
        ('FAILED', 'Failed'),
        ('REVIEW', 'Needs Review')
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')

    # Path to the root directory where the generated project files are stored on the server
    # This path should be relative to MEDIA_ROOT or a designated storage location
    generated_path = models.CharField(max_length=500, blank=True, null=True,
                                      help_text="Relative path to the root directory of the generated project.")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Generated Project"
        verbose_name_plural = "Generated Projects"
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.status})"

class GeneratedFile(models.Model):
    """
    Represents an individual file generated as part of a project.
    Useful for detailed tracking and previewing.
    """
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='files')
    file_path = models.CharField(max_length=500, help_text="Path of the file relative to the project's root.")
    # You might store content in DB for small files, or just reference from disk
    # For large projects, storing content in DB is inefficient.
    # For preview, you'll read from `project.generated_path + file_path`
    # content = models.TextField(blank=True) 
    
    file_type = models.CharField(max_length=50, blank=True, help_text="e.g., 'python', 'javascript', 'html', 'json'")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Generated File"
        verbose_name_plural = "Generated Files"
        unique_together = ('project', 'file_path') # A file path should be unique per project

    def __str__(self):
        return f"{self.project.name}/{self.file_path}"
