# Generated by Django 5.2.1 on 2025-06-11 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the generated project', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Summary of the project generated by AI', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Generation'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW', 'Needs Review')], default='PENDING', max_length=20)),
                ('generated_path', models.CharField(blank=True, help_text='Relative path to the root directory of the generated project.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who initiated this project generation.', on_delete=django.db.models.deletion.CASCADE, related_name='generated_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Project',
                'verbose_name_plural': 'Generated Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text="Path of the file relative to the project's root.", max_length=500)),
                ('file_type', models.CharField(blank=True, help_text="e.g., 'python', 'javascript', 'html', 'json'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project')),
            ],
            options={
                'verbose_name': 'Generated File',
                'verbose_name_plural': 'Generated Files',
                'unique_together': {('project', 'file_path')},
            },
        ),
    ]
