# Generated by Django 5.2.1 on 2025-06-12 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who initiated this project generation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
